---
pipeline: REPO1
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: false
  well_column: Metadata_Well
  external :
    perform: false
    file: <metadata file name>
    merge_column: <Column to merge on>
normalize:
  perform: false
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
normalize_negcon:
  perform: false
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: batch
  gct: true
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: false
  features: infer
  level: batch
  gct: true
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2022_11_28_Batch1
plates:
  - name: BR00135658
    process: true
  - name: BR00135659
    process: true
  - name: BR00135660         
    process: true
  - name: BR00135661         
    process: true
  - name: BR00135662         
    process: true
  - name: BR00135663         
    process: true
  - name: BR00135665         
    process: true
  - name: BR00135666         
    process: true
  - name: BR00135667         
    process: true
  - name: BR00135668         
    process: true
  - name: BR00135670         
    process: true
  - name: BR00135671         
    process: true
  - name: BR00135672         
    process: true
  - name: BR00135673         
    process: true
  - name: BR00135675         
    process: true
  - name: BR00135676         
    process: true
  - name: BR00135677         
    process: true
  - name: BR00135678         
    process: true
  - name: BR00135656         
    process: true
  - name: BR00135657         
    process: true
  - name: BR00135664         
    process: true
  - name: BR00135669         
    process: true
  - name: BR00135674         
    process: true
  - name: BR00135679         
    process: true
process: true
